# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.sis3316Tab = QtWidgets.QWidget()
        self.sis3316Tab.setObjectName("sis3316Tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sis3316Tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.sis3316Tab)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.horizontalLayout_3.addWidget(self.lineEdit_ip)
        self.ipConnectButton = QtWidgets.QPushButton(self.frame_4)
        self.ipConnectButton.setObjectName("ipConnectButton")
        self.horizontalLayout_3.addWidget(self.ipConnectButton)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.sis3316Tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_config = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_config.setStyleSheet("")
        self.lineEdit_config.setText("")
        self.lineEdit_config.setObjectName("lineEdit_config")
        self.horizontalLayout_2.addWidget(self.lineEdit_config)
        self.configFileButton = QtWidgets.QPushButton(self.frame_3)
        self.configFileButton.setObjectName("configFileButton")
        self.horizontalLayout_2.addWidget(self.configFileButton)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.sis3316Tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_folder = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_folder.setObjectName("lineEdit_folder")
        self.horizontalLayout.addWidget(self.lineEdit_folder)
        self.outputFolderButton = QtWidgets.QPushButton(self.frame)
        self.outputFolderButton.setObjectName("outputFolderButton")
        self.horizontalLayout.addWidget(self.outputFolderButton)
        self.verticalLayout_2.addWidget(self.frame)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.sis3316Tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.frame_channels = QtWidgets.QFrame(self.sis3316Tab)
        self.frame_channels.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_channels.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_channels.setObjectName("frame_channels")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_channels)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_0 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_0.setObjectName("checkBox_0")
        self.gridLayout.addWidget(self.checkBox_0, 0, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 0, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 0, 2, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 0, 3, 1, 1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout.addWidget(self.checkBox_1, 1, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 1, 1, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 1, 2, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout.addWidget(self.checkBox_13, 1, 3, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 2, 1, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 2, 2, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout.addWidget(self.checkBox_14, 2, 3, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 3, 1, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout.addWidget(self.checkBox_11, 3, 2, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout.addWidget(self.checkBox_15, 3, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_channels)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.startButton = QtWidgets.QPushButton(self.sis3316Tab)
        self.startButton.setMinimumSize(QtCore.QSize(0, 0))
        self.startButton.setBaseSize(QtCore.QSize(0, 0))
        self.startButton.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_4.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.sis3316Tab)
        self.stopButton.setMinimumSize(QtCore.QSize(0, 0))
        self.stopButton.setBaseSize(QtCore.QSize(0, 0))
        self.stopButton.setStyleSheet("background-color: rgb(233, 185, 110);")
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_4.addWidget(self.stopButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.sis3316Tab)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 4, 0, 1, 1)
        self.tabWidget.addTab(self.sis3316Tab, "")
        self.channelTab = QtWidgets.QWidget()
        self.channelTab.setObjectName("channelTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.channelTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_channel = QtWidgets.QComboBox(self.channelTab)
        self.comboBox_channel.setObjectName("comboBox_channel")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.comboBox_channel.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_channel)
        self.frame1 = QtWidgets.QFrame(self.channelTab)
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        self.frame2 = QtWidgets.QFrame(self.frame1)
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_raw = QtWidgets.QLabel(self.frame2)
        self.label_raw.setObjectName("label_raw")
        self.gridLayout_6.addWidget(self.label_raw, 0, 0, 1, 1)
        self.checkBox_adcRaw = QtWidgets.QCheckBox(self.frame2)
        self.checkBox_adcRaw.setObjectName("checkBox_adcRaw")
        self.gridLayout_6.addWidget(self.checkBox_adcRaw, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame2)
        self.label_8.setStyleSheet("font: italic 8pt \"Ubuntu\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 2)
        self.gridLayout_5.addWidget(self.frame2, 4, 0, 1, 2)
        self.frame3 = QtWidgets.QFrame(self.frame1)
        self.frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3.setObjectName("frame3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.frame3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.checkBox_peakMax = QtWidgets.QCheckBox(self.frame3)
        self.checkBox_peakMax.setObjectName("checkBox_peakMax")
        self.horizontalLayout_8.addWidget(self.checkBox_peakMax)
        self.gridLayout_5.addWidget(self.frame3, 3, 0, 1, 2)
        self.frame4 = QtWidgets.QFrame(self.frame1)
        self.frame4.setStyleSheet("border-color: rgb(136, 138, 133);")
        self.frame4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame4.setObjectName("frame4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radio_gain5V = QtWidgets.QRadioButton(self.frame4)
        self.radio_gain5V.setObjectName("radio_gain5V")
        self.horizontalLayout_5.addWidget(self.radio_gain5V)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.radio_gain2V = QtWidgets.QRadioButton(self.frame4)
        self.radio_gain2V.setObjectName("radio_gain2V")
        self.horizontalLayout_5.addWidget(self.radio_gain2V)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.radio_gain19V = QtWidgets.QRadioButton(self.frame4)
        self.radio_gain19V.setStyleSheet("border-color: rgb(136, 138, 133);")
        self.radio_gain19V.setObjectName("radio_gain19V")
        self.horizontalLayout_5.addWidget(self.radio_gain19V)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout_5.addWidget(self.frame4, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_channel = QtWidgets.QLabel(self.frame1)
        self.label_channel.setStyleSheet("font: 13pt \"Ubuntu\";")
        self.label_channel.setObjectName("label_channel")
        self.gridLayout_5.addWidget(self.label_channel, 0, 0, 1, 2)
        self.frame5 = QtWidgets.QFrame(self.frame1)
        self.frame5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame5.setObjectName("frame5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.frame5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.checkBox_invert = QtWidgets.QCheckBox(self.frame5)
        self.checkBox_invert.setObjectName("checkBox_invert")
        self.horizontalLayout_7.addWidget(self.checkBox_invert)
        self.gridLayout_5.addWidget(self.frame5, 5, 0, 1, 2)
        self.frame6 = QtWidgets.QFrame(self.frame1)
        self.frame6.setObjectName("frame6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_threshold = QtWidgets.QLineEdit(self.frame6)
        self.lineEdit_threshold.setObjectName("lineEdit_threshold")
        self.horizontalLayout_6.addWidget(self.lineEdit_threshold)
        self.label_11 = QtWidgets.QLabel(self.frame6)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gridLayout_5.addWidget(self.frame6, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frame1)
        self.horizontalFrame = QtWidgets.QFrame(self.channelTab)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.channelConfigButton = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelConfigButton.sizePolicy().hasHeightForWidth())
        self.channelConfigButton.setSizePolicy(sizePolicy)
        self.channelConfigButton.setMaximumSize(QtCore.QSize(300, 50))
        self.channelConfigButton.setObjectName("channelConfigButton")
        self.horizontalLayout_11.addWidget(self.channelConfigButton)
        self.label_7 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_7.setStyleSheet("font: 8pt \"Ubuntu\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.verticalLayout_4.addWidget(self.horizontalFrame)
        self.tabWidget.addTab(self.channelTab, "")
        self.helpTab = QtWidgets.QWidget()
        self.helpTab.setObjectName("helpTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.helpTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textBrowser_help = QtWidgets.QTextBrowser(self.helpTab)
        self.textBrowser_help.setObjectName("textBrowser_help")
        self.gridLayout_3.addWidget(self.textBrowser_help, 0, 0, 1, 1)
        self.tabWidget.addTab(self.helpTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.configFileButton.released.connect(MainWindow.slotBrowseConfig)
        self.outputFolderButton.released.connect(MainWindow.slotBrowseOutput)
        self.lineEdit_ip.returnPressed.connect(MainWindow.slotIpAddress)
        self.lineEdit_config.returnPressed.connect(MainWindow.slotConfig)
        self.lineEdit_folder.returnPressed.connect(MainWindow.slotOutput)
        self.startButton.released.connect(MainWindow.slotStart)
        self.stopButton.released.connect(MainWindow.slotStop)
        self.ipConnectButton.released.connect(MainWindow.slotIpConnect)
        self.comboBox_channel.currentIndexChanged['QString'].connect(MainWindow.slotChannelChange)
        self.tabWidget.currentChanged['int'].connect(MainWindow.slotTabChanged)
        self.channelConfigButton.released.connect(MainWindow.slotChannelConfig)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "sis3316"))
        self.label_4.setText(_translate("MainWindow", "IP Address      "))
        self.ipConnectButton.setText(_translate("MainWindow", "Check Connection"))
        self.label_3.setText(_translate("MainWindow", "Config File      "))
        self.configFileButton.setText(_translate("MainWindow", "Load"))
        self.label.setText(_translate("MainWindow", "Output folder"))
        self.outputFolderButton.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Channel readout"))
        self.checkBox_0.setText(_translate("MainWindow", "0"))
        self.checkBox_4.setText(_translate("MainWindow", "4"))
        self.checkBox_8.setText(_translate("MainWindow", "8"))
        self.checkBox_12.setText(_translate("MainWindow", "12"))
        self.checkBox_1.setText(_translate("MainWindow", "1"))
        self.checkBox_5.setText(_translate("MainWindow", "5"))
        self.checkBox_9.setText(_translate("MainWindow", "9"))
        self.checkBox_13.setText(_translate("MainWindow", "13"))
        self.checkBox_2.setText(_translate("MainWindow", "2"))
        self.checkBox_6.setText(_translate("MainWindow", "6"))
        self.checkBox_10.setText(_translate("MainWindow", "10"))
        self.checkBox_14.setText(_translate("MainWindow", "14"))
        self.checkBox_3.setText(_translate("MainWindow", "3"))
        self.checkBox_7.setText(_translate("MainWindow", "7"))
        self.checkBox_11.setText(_translate("MainWindow", "11"))
        self.checkBox_15.setText(_translate("MainWindow", "15"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sis3316Tab), _translate("MainWindow", "sis3316"))
        self.comboBox_channel.setItemText(0, _translate("MainWindow", "Ch0"))
        self.comboBox_channel.setItemText(1, _translate("MainWindow", "Ch1"))
        self.comboBox_channel.setItemText(2, _translate("MainWindow", "Ch2"))
        self.comboBox_channel.setItemText(3, _translate("MainWindow", "Ch3"))
        self.comboBox_channel.setItemText(4, _translate("MainWindow", "Ch4"))
        self.comboBox_channel.setItemText(5, _translate("MainWindow", "Ch5"))
        self.comboBox_channel.setItemText(6, _translate("MainWindow", "Ch6"))
        self.comboBox_channel.setItemText(7, _translate("MainWindow", "Ch7"))
        self.comboBox_channel.setItemText(8, _translate("MainWindow", "Ch8"))
        self.comboBox_channel.setItemText(9, _translate("MainWindow", "Ch9"))
        self.comboBox_channel.setItemText(10, _translate("MainWindow", "Ch10"))
        self.comboBox_channel.setItemText(11, _translate("MainWindow", "Ch11"))
        self.comboBox_channel.setItemText(12, _translate("MainWindow", "Ch12"))
        self.comboBox_channel.setItemText(13, _translate("MainWindow", "Ch13"))
        self.comboBox_channel.setItemText(14, _translate("MainWindow", "Ch14"))
        self.comboBox_channel.setItemText(15, _translate("MainWindow", "Ch15"))
        self.label_6.setText(_translate("MainWindow", "Threshold"))
        self.label_raw.setText(_translate("MainWindow", "Read raw waveform (ch 0 - 3)"))
        self.checkBox_adcRaw.setText(_translate("MainWindow", "Enabled"))
        self.label_8.setText(_translate("MainWindow", "Caution: will result in large files and may result in dropped packets if \n"
"signal rate is high. Use only for initial callibration purposes!"))
        self.label_10.setText(_translate("MainWindow", "Read ADC peak max"))
        self.checkBox_peakMax.setText(_translate("MainWindow", "Enabled"))
        self.radio_gain5V.setText(_translate("MainWindow", "5V"))
        self.radio_gain2V.setText(_translate("MainWindow", "2V"))
        self.radio_gain19V.setText(_translate("MainWindow", "1.9 V"))
        self.label_5.setText(_translate("MainWindow", "Gain range"))
        self.label_channel.setText(_translate("MainWindow", "-- Channel 0 --"))
        self.label_12.setText(_translate("MainWindow", "Invert ADC input"))
        self.checkBox_invert.setText(_translate("MainWindow", "Enabled"))
        self.label_11.setText(_translate("MainWindow", "+ 0x800 0000"))
        self.channelConfigButton.setText(_translate("MainWindow", "Apply settings"))
        self.label_7.setText(_translate("MainWindow", "Note: feel free to adjust the settings\n"
"of multiple channels before hitting this button"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.channelTab), _translate("MainWindow", "Channel options"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.helpTab), _translate("MainWindow", "Help"))
